<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.2.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IrigPoker.Application\IrigPoker.Application.csproj" />
    <ProjectReference Include="..\IrigPoker.Common\IrigPoker.Common.csproj" />
    <ProjectReference Include="..\IrigPoker.Implementation\IrigPoker.Implementation.csproj" />
  </ItemGroup>

</Project>
