name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build BE Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/irig-poker-api:latest ./src/backend

      - name: Push BE Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/irig-poker-api:latest

      - name: Build FE Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.actor }}/irig-poker-ui:latest \
            --build-arg VITE_API_BASE_URL= \
            ./src/frontend

      - name: Push FE Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/irig-poker-ui:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ${{ vars.DOCKER_COMPOSE_DIR }}
            docker compose pull
            docker compose up -d
